name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: throw-if-null/alembic/alembic
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_RW_PAT }}
          registry: docker.pkg.github.com
          default_branch: branch-zero
          dockerfile: ./Alembic/Dockerfile
          context: .