name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Semver
      uses: MirzaMerdovic/docker-semver-github-action@1.3.2
      with:
        name: mirzamerdovic/alembic
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile:  ./Dockerfile 
        context: .
